name              : string-matching
version           : '0.1.0.0'
category          : Web
author            : Ivan Yudin
maintainer        : yudinivan@yahoo.de
copyright         : 2019 Ivan Yudin
license           : BSD3
github            : Ivan-Yudin/aho-corasick-trie
extra-source-files:
- README.md
dependencies      :
-  base                
-  containers          
-  data-default-class
-  hashable            
-  ListLike            
-  profunctors         

executables:
 intmap: 
  source-dirs  :  src        
  main         :  Intmap
  ghc-options  :
  - -O2
  - -split-sections

library           :
  source-dirs     : lib
  exposed-modules :
  - Data.Tree.KMPTree
  - Data.Tree.AhoCorasickTrie
  - Data.MapLike
  - Data.Maybe_
