name              : string-matching
version           : '0.1.0.0'
category          : Web
author            : Ivan Yudin
maintainer        : yudinivan@yahoo.de
copyright         : 2019 Ivan Yudin
license           : BSD3
github            : Ivan-Yudin/string-matching
extra-source-files:
- README.md
dependencies      :
- base >=4.7 && <5
- containers 
- data-default-class
- hashable >= 1.2.7 && < 1.3
- ListLike >=4.6 && < 4.7
- profunctors >= 5.2 && < 5.4
library           :
  source-dirs     : src
  exposed-modules :
  - Data.Tree.ACTree 
